2018-07-28 18:42:58,690 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/warrenbain/Projects/personal/microblog/app/auth/routes.py", line 60, in reset_password_request
    send_password_reset_email(user)
  File "/Users/warrenbain/Projects/personal/microblog/app/auth/email.py", line 6, in send_password_reset_email
    from app.email import send_mail
ImportError: cannot import name 'send_mail' from 'app.email' (/Users/warrenbain/Projects/personal/microblog/app/email.py)
2018-07-28 18:52:34,255 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:83]
2018-07-28 18:52:47,639 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:83]
2018-07-28 19:08:32,472 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:83]
