2018-07-12 22:00:12,035 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:43]
2018-07-12 22:00:24,908 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:43]
2018-07-12 22:10:23,783 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:43]
2018-07-14 21:38:36,270 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:52]
2018-07-14 21:53:39,955 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:52]
2018-07-14 21:54:20,628 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:52]
2018-07-14 21:57:40,165 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:52]
2018-07-15 21:40:11,888 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:78]
2018-07-15 21:40:43,285 ERROR: Exception on /search [GET] [in /Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/warrenbain/Projects/personal/microblog/app/main/routes.py", line 141, in search
    posts, total = Post.search(g.search_form.q.data, page,
AttributeError: type object 'Post' has no attribute 'search'
2018-07-15 21:42:18,124 ERROR: Exception on /search [GET] [in /Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/warrenbain/Projects/personal/microblog/app/main/routes.py", line 141, in search
    posts, total = Post.search(g.search_form.q.data, page,
AttributeError: type object 'Post' has no attribute 'search'
2018-07-15 21:43:14,528 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:78]
2018-07-15 21:44:27,290 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:78]
2018-07-15 21:44:30,809 ERROR: Exception on /search [GET] [in /Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/warrenbain/Projects/personal/microblog/app/main/routes.py", line 141, in search
    posts, total = Post.search(g.search_form.q.data, page,
AttributeError: type object 'Post' has no attribute 'search'
2018-07-15 21:54:45,552 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:78]
2018-07-15 21:54:52,986 ERROR: Exception on /search [GET] [in /Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/warrenbain/Projects/personal/microblog/app/main/routes.py", line 142, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/Users/warrenbain/Projects/personal/microblog/app/models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/warrenbain/Projects/personal/microblog/app/search.py", line 23, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 636, in search
    doc_type, '_search'), params=params, body=body)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 163, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/warrenbain/Projects/personal/microblog/venv/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')
2018-07-15 21:57:55,619 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:78]
2018-07-15 22:04:12,227 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:78]
2018-07-15 22:04:48,164 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:78]
2018-07-18 22:08:47,078 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:78]
2018-07-18 22:09:16,476 INFO: Microblog startup [in /Users/warrenbain/Projects/personal/microblog/app/__init__.py:78]
